### ISSUE TITLE
Change demodulated function

### ISSUE THREAD

**Issue by Vskilet** [Vskilet/UMTS-Multiplexing#1]
We just need ID of the phone and not the cellPhone entirely

**Comment by kwidz** [comment]
No ID does not deserve, we need phone for debuging function and it doesn't change speed of code if you change this. DON'T DO THIS, IT WORKS !

**Comment by kwidz** [comment]
btw arguments are passed as reference, so dont consume memory.....

**Comment by Vskilet** [comment]
You right but it oblige us to traverse all table of mobile each time we print something on screen.

**Comment by kwidz** [comment]
you don't have to use the demodulate function to print something on screen, and you don't have to parse the table of mobile each time you use the demodulate function, if you want to demodulate the signal for one mobile just call the demodulate function with listMobile[id]

**Comment by Vskilet** [comment]
Ok i see, I'll test it. Thanks

--
Victor SENE

Le 7 juin 2017 07:30, "Glangine Geoffrey" <notifications@github.com> a
écrit :
